In [1]:
###  Label Encoding involves assigning a unique label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories.

In [5]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [6]:
## Create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [7]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [8]:
lbl_encoder=LabelEncoder()

In [9]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\vikra\OneDrive\Pictures\Desktop\Code\venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [11]:
lbl_encoder.transform([['red']])

c:\Users\vikra\OneDrive\Pictures\Desktop\Code\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [12]:
#### Ordinal Encoding
### It is used to encode categrical data that have an intrinsic order or ranking,.Each category is assigned a numerical value based on its position in the order

In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [14]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [15]:
df.head()

     size
0   small
1  medium
2   large
3  medium
4   small

In [16]:
### create an instances of ordinaland then fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [17]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [18]:
encoder.transform([['small']])

c:\Users\vikra\OneDrive\Pictures\Desktop\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

In [19]:
### Target Guided Ordinal Encoding
### It is a technique to encode categorical variables based on their releationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories.

In [20]:
df=pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,180,320]
})

In [21]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [23]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [24]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [25]:
df['city_encoded']=df['city'].map(mean_price)

In [26]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [27]:
df[['city','city_encoded']]

       city  city_encoded
0  New York         190.0
1    London         150.0
2     Paris         310.0
3     Tokyo         250.0
4  New York         190.0
5     Paris         310.0

In [28]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]